// GENERATED by gen_trainer.js — do not hand-edit. Source: NEMO proctor scenario briefs + Emergency Care 14th ed. / Region X SOP overlays (textbook is the primary authority).
// Contains scenario content only — nothing from the proctor access-controlled page is carried over.
window.TRAINER_SHEETS = {
 "medical": {
  "label": "Medical",
  "sections": [
   {
    "title": "Scene Size-Up",
    "items": [
     {
      "item": "Takes or verbalizes appropriate BSI/PPE precautions",
      "treatment": false
     },
     {
      "item": "Determines the scene/situation is safe",
      "treatment": false
     },
     {
      "item": "Determines the mechanism of injury or nature of illness",
      "treatment": false
     },
     {
      "item": "Determines the number of patients",
      "treatment": false
     },
     {
      "item": "Requests additional help (ALS, PD, FD) if necessary",
      "treatment": false
     }
    ]
   },
   {
    "title": "Primary Assessment — General Impression",
    "items": [
     {
      "item": "Patient description (age, sex assigned at birth)",
      "treatment": false
     },
     {
      "item": "Determines responsiveness — AVPU",
      "treatment": false
     },
     {
      "item": "If alert → A&O out of 4 (who/where/when/general)",
      "treatment": false
     },
     {
      "item": "Considers spine stabilization",
      "treatment": false
     },
     {
      "item": "Determines apparent life threats",
      "treatment": false
     },
     {
      "item": "Determines chief complaint",
      "treatment": false
     }
    ]
   },
   {
    "title": "Primary Assessment — Airway",
    "items": [
     {
      "item": "Identifies if there is an obstruction",
      "treatment": false
     },
     {
      "item": "Opens/clears airway if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Primary Assessment — Breathing",
    "items": [
     {
      "item": "Tidal volume (adequate chest rise/fall)",
      "treatment": false
     },
     {
      "item": "Relative rate (fast, slow, regular)",
      "treatment": false
     },
     {
      "item": "Respiratory pattern (regular, irregular)",
      "treatment": false
     },
     {
      "item": "Accessory muscle use",
      "treatment": false
     },
     {
      "item": "SpO₂",
      "treatment": false
     },
     {
      "item": "Lung sounds",
      "treatment": false
     },
     {
      "item": "Initiates appropriate oxygen therapy / ventilatory mgmt if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Primary Assessment — Circulation",
    "items": [
     {
      "item": "Assess/control major bleeding",
      "treatment": false
     },
     {
      "item": "Color",
      "subgroup": "Skin",
      "treatment": false
     },
     {
      "item": "Temperature",
      "subgroup": "Skin",
      "treatment": false
     },
     {
      "item": "Moisture",
      "subgroup": "Skin",
      "treatment": false
     },
     {
      "item": "Strength (weak, strong, bounding)",
      "subgroup": "Pulse",
      "treatment": false
     },
     {
      "item": "Rate (fast, slow, regular)",
      "subgroup": "Pulse",
      "treatment": false
     },
     {
      "item": "Regularity (regular, irregular)",
      "subgroup": "Pulse",
      "treatment": false
     },
     {
      "item": "Equality (symmetrical, asymmetrical)",
      "subgroup": "Pulse",
      "treatment": false
     },
     {
      "item": "Capillary refill",
      "treatment": false
     },
     {
      "item": "Identify if patient is in shock",
      "treatment": false
     },
     {
      "item": "If shock → initiate shock treatment",
      "treatment": true
     },
     {
      "item": "Identify patient priority (stable/unstable) and transport decision",
      "treatment": false
     }
    ]
   },
   {
    "title": "History — OPQRST (History of Present Illness)",
    "items": [
     {
      "item": "Onset",
      "treatment": false
     },
     {
      "item": "Provocation / palliation",
      "treatment": false
     },
     {
      "item": "Quality",
      "treatment": false
     },
     {
      "item": "Radiation",
      "treatment": false
     },
     {
      "item": "Severity",
      "treatment": false
     },
     {
      "item": "Time",
      "treatment": false
     }
    ]
   },
   {
    "title": "History — AMPLE (Past Medical)",
    "items": [
     {
      "item": "Allergies",
      "treatment": false
     },
     {
      "item": "Medications",
      "treatment": false
     },
     {
      "item": "Past pertinent medical history",
      "treatment": false
     },
     {
      "item": "Last oral intake",
      "treatment": false
     },
     {
      "item": "Events leading up to present illness",
      "treatment": false
     }
    ]
   },
   {
    "title": "Vital Signs",
    "items": [
     {
      "item": "Blood pressure",
      "treatment": false
     },
     {
      "item": "Pulse rate and quality",
      "treatment": false
     },
     {
      "item": "Ventilatory rate and quality",
      "treatment": false
     }
    ]
   },
   {
    "title": "Diagnostics",
    "items": [
     {
      "item": "Blood glucose level",
      "treatment": false
     },
     {
      "item": "SpO₂",
      "treatment": false
     }
    ]
   },
   {
    "title": "Field Impression & Reassessment",
    "items": [
     {
      "item": "States field impression of patient",
      "treatment": false
     },
     {
      "item": "Administers proper treatment",
      "treatment": true
     },
     {
      "item": "Determines reassessment frequency & re-evaluates transport decision",
      "treatment": false
     },
     {
      "item": "Repeats primary assessment",
      "treatment": false
     },
     {
      "item": "Evaluates response to treatments",
      "treatment": false
     },
     {
      "item": "Reassesses patient complaints",
      "treatment": false
     },
     {
      "item": "Provides accurate verbal report to receiving facility",
      "treatment": false
     }
    ]
   }
  ],
  "complaints": {
   "respiratory": {
    "label": "Respiratory",
    "sections": [
     {
      "title": "Respiratory — Associated Signs & Symptoms",
      "treatmentSection": false,
      "items": [
       {
        "item": "Chest pain",
        "treatment": false
       },
       {
        "item": "Weakness",
        "treatment": false
       },
       {
        "item": "Fever",
        "treatment": false
       },
       {
        "item": "Swollen hands or feet",
        "treatment": false
       },
       {
        "item": "Cough",
        "treatment": false
       }
      ]
     },
     {
      "title": "Respiratory — Specific Questions",
      "treatmentSection": false,
      "items": [
       {
        "item": "Respiratory infection / symptoms of one?",
        "treatment": false
       },
       {
        "item": "Cough? Productive? What coughing up?",
        "treatment": false
       },
       {
        "item": "More comfortable in any position?",
        "treatment": false
       }
      ]
     },
     {
      "title": "Respiratory — Focused Assessment",
      "treatmentSection": false,
      "items": [
       {
        "item": "Look: accessory muscle use",
        "treatment": false
       },
       {
        "item": "Look: tracheal tugging",
        "treatment": false
       },
       {
        "item": "Look: jugular vein distention (JVD)",
        "treatment": false
       },
       {
        "item": "Look: abnormal positioning",
        "treatment": false
       },
       {
        "item": "Listen: breath sounds (grunting, wheezing, rales, stridor)",
        "treatment": false
       },
       {
        "item": "Feel: tracheal deviation",
        "treatment": false
       }
      ]
     },
     {
      "title": "Respiratory — Treatment",
      "treatmentSection": true,
      "items": [
       {
        "item": "Proper oxygen therapy",
        "treatment": true
       },
       {
        "item": "If wheezing → 2.5 mg Albuterol + 0.5 mg Atrovent via nebulizer",
        "treatment": true
       }
      ]
     }
    ]
   },
   "cardiac": {
    "label": "Cardiac",
    "sections": [
     {
      "title": "Cardiac — Associated Signs & Symptoms",
      "treatmentSection": false,
      "items": [
       {
        "item": "Shortness of breath",
        "treatment": false
       },
       {
        "item": "Weakness",
        "treatment": false
       },
       {
        "item": "Dizziness",
        "treatment": false
       },
       {
        "item": "Palpitations",
        "treatment": false
       }
      ]
     },
     {
      "title": "Cardiac — Specific Questions",
      "treatmentSection": false,
      "items": [
       {
        "item": "Respiratory infection / symptoms?",
        "treatment": false
       },
       {
        "item": "Cough? Productive? What coughing up?",
        "treatment": false
       },
       {
        "item": "Does pain change with movement or deep breath?",
        "treatment": false
       }
      ]
     },
     {
      "title": "Cardiac — Focused Assessment",
      "treatmentSection": false,
      "items": [
       {
        "item": "Look: JVD",
        "treatment": false
       },
       {
        "item": "Look: peripheral edema",
        "treatment": false
       },
       {
        "item": "Look: pursed-lip breathing",
        "treatment": false
       },
       {
        "item": "Look: pink frothy sputum",
        "treatment": false
       },
       {
        "item": "Listen: breath sounds",
        "treatment": false
       }
      ]
     },
     {
      "title": "Cardiac — Treatment",
      "treatmentSection": true,
      "items": [
       {
        "item": "Proper oxygen therapy",
        "treatment": true
       },
       {
        "item": "If indicated → 324 mg Aspirin",
        "treatment": true
       },
       {
        "item": "If indicated → 0.4 mg Nitroglycerin",
        "treatment": true
       }
      ]
     }
    ]
   },
   "neurological": {
    "label": "Neurological",
    "sections": [
     {
      "title": "Neuro — Associated Signs & Symptoms",
      "treatmentSection": false,
      "items": [
       {
        "item": "Headache",
        "treatment": false
       },
       {
        "item": "Blurred vision",
        "treatment": false
       },
       {
        "item": "Cloudiness or confusion",
        "treatment": false
       },
       {
        "item": "Other noticeable deficits",
        "treatment": false
       }
      ]
     },
     {
      "title": "Neuro — Specific Questions",
      "treatmentSection": false,
      "items": [
       {
        "item": "Seeing/hearing things not there?",
        "treatment": false
       },
       {
        "item": "Want to hurt yourself or others?",
        "treatment": false
       },
       {
        "item": "Is presentation normal for patient? What is different / when did it begin?",
        "treatment": false
       },
       {
        "item": "Recent drugs or alcohol? When/what/how much?",
        "treatment": false
       },
       {
        "item": "History of diabetes? Recent blood sugars?",
        "treatment": false
       },
       {
        "item": "Fever?",
        "treatment": false
       },
       {
        "item": "Open wounds?",
        "treatment": false
       }
      ]
     },
     {
      "title": "Neuro — Focused Assessment",
      "treatmentSection": false,
      "items": [
       {
        "item": "Look: pupils (PEARL)",
        "treatment": false
       },
       {
        "item": "Look: drug/alcohol paraphernalia",
        "treatment": false
       },
       {
        "item": "Look: active seizure",
        "treatment": false
       },
       {
        "item": "Feel: head injuries",
        "treatment": false
       },
       {
        "item": "Feel: PMS (pulse, motor, sensory)",
        "treatment": false
       },
       {
        "item": "Cincinnati Stroke Scale (FAST)",
        "treatment": false
       },
       {
        "item": "Smell: fruity/acetone breath",
        "treatment": false
       },
       {
        "item": "Smell: alcohol on breath",
        "treatment": false
       }
      ]
     },
     {
      "title": "Neuro — Treatment",
      "treatmentSection": true,
      "items": [
       {
        "item": "Proper oxygen therapy",
        "treatment": true
       },
       {
        "item": "If hypoglycemic → 15 g oral glucose",
        "treatment": true
       },
       {
        "item": "If possible opiate OD → 2 mg Narcan intranasally",
        "treatment": true
       },
       {
        "item": "If risky weather → remove patient from environment",
        "treatment": true
       }
      ]
     }
    ]
   },
   "anaphylaxis": {
    "label": "Anaphylaxis",
    "sections": [
     {
      "title": "Anaphylaxis — Associated Signs & Symptoms",
      "treatmentSection": false,
      "items": [
       {
        "item": "Weakness",
        "treatment": false
       },
       {
        "item": "Shortness of breath",
        "treatment": false
       },
       {
        "item": "Itchiness",
        "treatment": false
       },
       {
        "item": "Chest pain",
        "treatment": false
       }
      ]
     },
     {
      "title": "Anaphylaxis — Specific Questions",
      "treatmentSection": false,
      "items": [
       {
        "item": "Encountered known allergen?",
        "treatment": false
       },
       {
        "item": "Taken anything to treat? (EpiPen, inhaler, Benadryl)",
        "treatment": false
       },
       {
        "item": "New medications, foods, or cleaning products?",
        "treatment": false
       }
      ]
     },
     {
      "title": "Anaphylaxis — Focused Assessment",
      "treatmentSection": false,
      "items": [
       {
        "item": "Look: accessory muscle use",
        "treatment": false
       },
       {
        "item": "Look: abnormal positioning (tripod, sniffing)",
        "treatment": false
       },
       {
        "item": "Look: peripheral edema",
        "treatment": false
       },
       {
        "item": "Look: facial swelling",
        "treatment": false
       },
       {
        "item": "Listen: breath sounds",
        "treatment": false
       }
      ]
     },
     {
      "title": "Anaphylaxis — Treatment",
      "treatmentSection": true,
      "items": [
       {
        "item": "Proper oxygen therapy",
        "treatment": true
       },
       {
        "item": "If wheezing → 2.5 mg Albuterol + 0.5 mg Atrovent",
        "treatment": true
       },
       {
        "item": "If anaphylactic → 0.3 mg Epinephrine (0.15 mg if under 66 lbs)",
        "treatment": true
       }
      ]
     }
    ]
   },
   "abdominal": {
    "label": "Abdominal",
    "sections": [
     {
      "title": "Abdominal — Associated Signs & Symptoms",
      "treatmentSection": false,
      "items": [
       {
        "item": "Weakness",
        "treatment": false
       },
       {
        "item": "Shortness of breath",
        "treatment": false
       },
       {
        "item": "Chest pain",
        "treatment": false
       }
      ]
     },
     {
      "title": "Abdominal — Specific Questions",
      "treatmentSection": false,
      "items": [
       {
        "item": "Vomiting? Describe; coffee-ground emesis or BRB?",
        "treatment": false
       },
       {
        "item": "Unusual bowel habits? Describe; dark tarry stool?",
        "treatment": false
       },
       {
        "item": "Pain with urination? Unusual odors? Urine appearance?",
        "treatment": false
       },
       {
        "item": "If female: vaginal discharge? Could be pregnant?",
        "treatment": false
       }
      ]
     },
     {
      "title": "Abdominal — Focused Assessment",
      "treatmentSection": false,
      "items": [
       {
        "item": "Look: discoloration",
        "treatment": false
       },
       {
        "item": "Look: distention",
        "treatment": false
       },
       {
        "item": "Look: obvious injury",
        "treatment": false
       },
       {
        "item": "Look: swelling",
        "treatment": false
       },
       {
        "item": "Look: visible masses",
        "treatment": false
       },
       {
        "item": "Listen: periodic bowel sounds",
        "treatment": false
       },
       {
        "item": "Palpate quadrants: tenderness",
        "treatment": false
       },
       {
        "item": "Palpate quadrants: rebound tenderness",
        "treatment": false
       },
       {
        "item": "Palpate quadrants: guarding/rigidity",
        "treatment": false
       },
       {
        "item": "Palpate quadrants: unusual masses",
        "treatment": false
       }
      ]
     },
     {
      "title": "Abdominal — Treatment",
      "treatmentSection": true,
      "items": [
       {
        "item": "Proper oxygen therapy",
        "treatment": true
       }
      ]
     }
    ]
   }
  }
 },
 "trauma": {
  "label": "Trauma",
  "sections": [
   {
    "title": "Scene Size-Up",
    "items": [
     {
      "item": "Takes or verbalizes appropriate BSI/PPE precautions",
      "treatment": false
     },
     {
      "item": "Determines the scene/situation is safe",
      "treatment": false
     },
     {
      "item": "Determines the mechanism of injury or nature of illness",
      "treatment": false
     },
     {
      "item": "Determines the number of patients",
      "treatment": false
     },
     {
      "item": "Requests additional help (ALS, PD, FD) if necessary",
      "treatment": false
     }
    ]
   },
   {
    "title": "Primary Assessment — General Impression",
    "items": [
     {
      "item": "Patient description (age, sex assigned at birth)",
      "treatment": false
     },
     {
      "item": "Determines responsiveness — AVPU",
      "treatment": false
     },
     {
      "item": "If alert → A&O out of 4",
      "treatment": false
     },
     {
      "item": "Considers spine stabilization",
      "treatment": false
     },
     {
      "item": "Determines apparent life threats",
      "treatment": false
     },
     {
      "item": "Determines chief complaint",
      "treatment": false
     }
    ]
   },
   {
    "title": "Primary Assessment — Airway",
    "items": [
     {
      "item": "Identifies if there is an obstruction",
      "treatment": false
     },
     {
      "item": "Opens/clears airway if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Primary Assessment — Breathing",
    "items": [
     {
      "item": "Tidal volume",
      "treatment": false
     },
     {
      "item": "Relative rate",
      "treatment": false
     },
     {
      "item": "Respiratory pattern",
      "treatment": false
     },
     {
      "item": "Accessory muscle use",
      "treatment": false
     },
     {
      "item": "SpO₂",
      "treatment": false
     },
     {
      "item": "Lung sounds",
      "treatment": false
     },
     {
      "item": "Initiates oxygen therapy / ventilatory mgmt if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Primary Assessment — Circulation",
    "items": [
     {
      "item": "Assess/control major bleeding",
      "treatment": false
     },
     {
      "item": "Color",
      "subgroup": "Skin",
      "treatment": false
     },
     {
      "item": "Temperature",
      "subgroup": "Skin",
      "treatment": false
     },
     {
      "item": "Moisture",
      "subgroup": "Skin",
      "treatment": false
     },
     {
      "item": "Strength (weak, strong, bounding)",
      "subgroup": "Pulse",
      "treatment": false
     },
     {
      "item": "Rate (fast, slow, regular)",
      "subgroup": "Pulse",
      "treatment": false
     },
     {
      "item": "Regularity (regular, irregular)",
      "subgroup": "Pulse",
      "treatment": false
     },
     {
      "item": "Equality (symmetrical, asymmetrical)",
      "subgroup": "Pulse",
      "treatment": false
     },
     {
      "item": "Capillary refill",
      "treatment": false
     },
     {
      "item": "Identify if patient is in shock",
      "treatment": false
     },
     {
      "item": "If shock → initiate shock treatment",
      "treatment": true
     },
     {
      "item": "Patient priority & transport decision",
      "treatment": false
     }
    ]
   },
   {
    "title": "Vital Signs",
    "items": [
     {
      "item": "Blood pressure",
      "treatment": false
     },
     {
      "item": "Pulse rate and quality",
      "treatment": false
     },
     {
      "item": "Ventilatory rate and quality",
      "treatment": false
     }
    ]
   },
   {
    "title": "Diagnostics",
    "items": [
     {
      "item": "Blood glucose level",
      "treatment": false
     },
     {
      "item": "SpO₂",
      "treatment": false
     }
    ]
   },
   {
    "title": "AMPLE History",
    "items": [
     {
      "item": "Allergies",
      "treatment": false
     },
     {
      "item": "Medications",
      "treatment": false
     },
     {
      "item": "Past pertinent history",
      "treatment": false
     },
     {
      "item": "Last oral intake",
      "treatment": false
     },
     {
      "item": "Events leading up",
      "treatment": false
     }
    ]
   },
   {
    "title": "Secondary — Head",
    "items": [
     {
      "item": "Inspect face & scalp for DCAP-BTLS",
      "treatment": false
     },
     {
      "item": "Inspect head for bleeding",
      "treatment": false
     },
     {
      "item": "Inspect for Raccoon Eyes",
      "treatment": false
     },
     {
      "item": "Inspect for Battle's Sign",
      "treatment": false
     },
     {
      "item": "Inspect ears & nose for fluid (CSF, blood)",
      "treatment": false
     },
     {
      "item": "Inspect mouth (missing teeth, injury, abnormal odors)",
      "treatment": false
     },
     {
      "item": "Assess eyes — PEARL",
      "treatment": false
     },
     {
      "item": "Palpate facial structures (crepitus, instability, deformity)",
      "treatment": false
     },
     {
      "item": "Treatment: head — control bleeding (direct pressure, soft tissue only)",
      "treatment": true
     }
    ]
   },
   {
    "title": "Secondary — Neck",
    "items": [
     {
      "item": "Inspect neck for DCAP-BTLS",
      "treatment": false
     },
     {
      "item": "Inspect neck for bleeding",
      "treatment": false
     },
     {
      "item": "Inspect for JVD",
      "treatment": false
     },
     {
      "item": "Inspect for subcutaneous emphysema on neck",
      "treatment": false
     },
     {
      "item": "Palpate trachea — deviation",
      "treatment": false
     },
     {
      "item": "Palpate cervical spine — inline, deformity, tenderness, fracture",
      "treatment": false
     },
     {
      "item": "Treatment: neck — control bleeding",
      "treatment": true
     },
     {
      "item": "Treatment: apply C-collar if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Secondary — Chest",
    "items": [
     {
      "item": "Inspect chest for DCAP-BTLS",
      "treatment": false
     },
     {
      "item": "Inspect chest for bleeding",
      "treatment": false
     },
     {
      "item": "Inspect for sucking chest wound on chest",
      "treatment": false
     },
     {
      "item": "Inspect for subcutaneous emphysema on chest",
      "treatment": false
     },
     {
      "item": "Inspect for paradoxical movement",
      "treatment": false
     },
     {
      "item": "Assess rate, tidal volume, rhythm, accessory muscle use",
      "treatment": false
     },
     {
      "item": "Palpate shoulders",
      "treatment": false
     },
     {
      "item": "Palpate clavicles",
      "treatment": false
     },
     {
      "item": "Palpate sternum",
      "treatment": false
     },
     {
      "item": "Palpate ribs",
      "treatment": false
     },
     {
      "item": "Listen to lung sounds",
      "treatment": false
     },
     {
      "item": "Treatment: chest — control bleeding",
      "treatment": true
     }
    ]
   },
   {
    "title": "Secondary — Abdomen",
    "items": [
     {
      "item": "Inspect abdomen for DCAP-BTLS",
      "treatment": false
     },
     {
      "item": "Inspect abdomen for bleeding",
      "treatment": false
     },
     {
      "item": "Inspect for evisceration",
      "treatment": false
     },
     {
      "item": "Inspect for bruising around umbilicus (Cullen's)",
      "treatment": false
     },
     {
      "item": "Inspect for bruising on flanks (Grey-Turner's)",
      "treatment": false
     },
     {
      "item": "Palpate all four quadrants — rigidity",
      "treatment": false
     },
     {
      "item": "Palpate quadrants — pulsating masses",
      "treatment": false
     },
     {
      "item": "Palpate quadrants — unusual masses",
      "treatment": false
     },
     {
      "item": "Treatment: abdomen — control bleeding",
      "treatment": true
     }
    ]
   },
   {
    "title": "Secondary — Pelvis",
    "items": [
     {
      "item": "Inspect pelvis for DCAP-BTLS",
      "treatment": false
     },
     {
      "item": "Inspect pelvis for bleeding",
      "treatment": false
     },
     {
      "item": "If male → inspect for priapism",
      "treatment": false
     },
     {
      "item": "Push pelvic bones together and down — crepitus, instability",
      "treatment": false
     },
     {
      "item": "Treatment: pelvis — control bleeding",
      "treatment": true
     },
     {
      "item": "Treatment: pelvis — immobilize if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Secondary — Lower Extremities",
    "items": [
     {
      "item": "Inspect lower extremities for DCAP-BTLS",
      "treatment": false
     },
     {
      "item": "Inspect lower extremities for bleeding",
      "treatment": false
     },
     {
      "item": "Assess each lower extremity for PMS",
      "treatment": false
     },
     {
      "item": "Palpate down lower extremities — crepitus, instability, deformity",
      "treatment": false
     },
     {
      "item": "Treatment: lower ext — control bleeding",
      "treatment": true
     },
     {
      "item": "Treatment: lower ext — splint area if fracture",
      "treatment": true
     },
     {
      "item": "Treatment: lower ext — immobilize if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Secondary — Upper Extremities",
    "items": [
     {
      "item": "Inspect upper extremities for DCAP-BTLS",
      "treatment": false
     },
     {
      "item": "Inspect upper extremities for bleeding",
      "treatment": false
     },
     {
      "item": "Assess each upper extremity for PMS",
      "treatment": false
     },
     {
      "item": "Palpate down upper extremities — crepitus, instability, deformity",
      "treatment": false
     },
     {
      "item": "Treatment: upper ext — control bleeding",
      "treatment": true
     },
     {
      "item": "Treatment: upper ext — splint area if fracture",
      "treatment": true
     },
     {
      "item": "Treatment: upper ext — immobilize if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Secondary — Posterior",
    "items": [
     {
      "item": "Inspect posterior for DCAP-BTLS",
      "treatment": false
     },
     {
      "item": "Inspect posterior for bleeding",
      "treatment": false
     },
     {
      "item": "Inspect for sucking chest wound on back",
      "treatment": false
     },
     {
      "item": "Inspect for subcutaneous emphysema on back",
      "treatment": false
     },
     {
      "item": "Palpate spine for crepitus, deformity, tenderness",
      "treatment": false
     },
     {
      "item": "Treatment: posterior — control bleeding",
      "treatment": true
     },
     {
      "item": "Treatment: posterior — immobilize if needed",
      "treatment": true
     }
    ]
   },
   {
    "title": "Field Impression & Reassessment",
    "items": [
     {
      "item": "States field impression of patient",
      "treatment": false
     },
     {
      "item": "Administers proper treatment",
      "treatment": true
     },
     {
      "item": "Determines reassessment frequency & re-evaluates transport decision",
      "treatment": false
     },
     {
      "item": "Repeats primary assessment",
      "treatment": false
     },
     {
      "item": "Evaluates response to treatments",
      "treatment": false
     },
     {
      "item": "Reassesses patient complaints",
      "treatment": false
     },
     {
      "item": "Provides accurate verbal report to receiving facility",
      "treatment": false
     }
    ]
   }
  ],
  "complaints": {}
 }
};
window.TRAINER_CRITICAL_FAILS = [
 "Failure to ensure scene safety prior to approaching patient",
 "Failure to take or verbalize appropriate BSI/PPE precautions",
 "Failure to initiate or call for transport within the 15-minute time limit",
 "Failure to provide appropriate oxygen therapy",
 "Failure to appropriately manage ABCs (airway, breathing, circulation)",
 "Orders a dangerous or inappropriate intervention",
 "Failure to provide accurate verbal report to receiving facility",
 "Failure to manage the patient as a competent EMT",
 "Exhibits unacceptable/unprofessional behavior with patient or other personnel"
];
window.TRAINER_SYNONYMS = {
 "Takes or verbalizes appropriate BSI/PPE precautions": [
  "\\bbsi\\b|\\bppe\\b|gloves|glasses|goggles|body substance|precaution|mask up"
 ],
 "Determines the scene/situation is safe": [
  "scene (is )?safe|scene safety|\\bsafety\\b|is it safe|hazard|danger|secure the scene"
 ],
 "Determines the mechanism of injury or nature of illness": [
  "\\bmoi\\b|\\bnoi\\b|mechanism|nature of (the )?illness|what happened|how did (this|it|that) happen"
 ],
 "Determines the number of patients": [
  "number of patients|how many (patients|people|victims)|other patients|anyone else (hurt|injured)"
 ],
 "Requests additional help (ALS, PD, FD) if necessary": [
  "\\bals\\b|paramedic|backup|back-up|additional (help|resources|units)|\\bpd\\b|\\bfd\\b|police|fire department|intercept|more (units|help)"
 ],
 "Patient description (age, sex assigned at birth)": [
  "general impression|patient description|how old|\\bage\\b|\\bsex\\b|describe the patient|who (am i|are we) (looking at|treating)"
 ],
 "Determines responsiveness — AVPU": [
  "\\bavpu\\b|responsive|level of consciousness|\\bloc\\b|conscious|arous|sternal rub|shoulder (tap|shake)|are you (ok|okay|awake)|can you hear me"
 ],
 "If alert → A&O out of 4 (who/where/when/general)": [
  "a ?& ?o|a&o|alert and oriented|orient|what('s| is) your name|where are you|what day|what happened to you"
 ],
 "If alert → A&O out of 4": [
  "a ?& ?o|a&o|alert and oriented|orient|what('s| is) your name|where are you|what day|what happened to you"
 ],
 "Considers spine stabilization": [
  "spin(e|al) (stab|motion|precaution|immobil)|c[- ]?spine|hold (the )?head|manual stabiliz|\\bsmr\\b|hold c-?spine|stabilize (the )?(head|neck)"
 ],
 "Determines apparent life threats": [
  "life threat|anything (obviously )?life[- ]threatening|obvious threats|immediate threats"
 ],
 "Determines chief complaint": [
  "chief complaint|\\bcc\\b|what('s| is) (wrong|going on|bothering)|why did you call|what brings|what seems to be"
 ],
 "Identifies if there is an obstruction": [
  "\\bairway\\b|obstruct|patent|patency|can you (talk|speak)|stridor|gurgl|snoring|look in (the|his|her) mouth|open (the )?airway|head[- ]tilt|jaw[- ]thrust"
 ],
 "Tidal volume (adequate chest rise/fall)": [
  "tidal|chest rise|rise and fall|depth of breath|adequate breath|breathing adequate"
 ],
 "Tidal volume": [
  "tidal|chest rise|rise and fall|depth of breath|adequate breath|breathing adequate"
 ],
 "Relative rate (fast, slow, regular)": [
  "respiratory rate|resp rate|\\brr\\b|count (the )?breath|respirations|breathing (fast|slow|rate)|how fast (is|are) (he|she|they) breathing"
 ],
 "Relative rate": [
  "respiratory rate|resp rate|\\brr\\b|count (the )?breath|respirations|breathing (fast|slow|rate)|how fast (is|are) (he|she|they) breathing"
 ],
 "Respiratory pattern (regular, irregular)": [
  "respiratory pattern|breathing pattern|regular breathing|irregular breathing|rhythm of breath|cheyne"
 ],
 "Respiratory pattern": [
  "respiratory pattern|breathing pattern|regular breathing|irregular breathing|rhythm of breath|cheyne"
 ],
 "Accessory muscle use": [
  "accessory|retraction|work of breathing|\\bwob\\b|labored|tripod|nasal flaring|tugging|effort"
 ],
 "SpO₂": [
  "spo2|spo₂|pulse ox|\\bsats?\\b|oxygen saturation|o2 sat|saturation"
 ],
 "Lung sounds": [
  "\\blungs?\\b|breath sounds|auscultat|listen to (the )?(chest|lungs)|wheez|\\brales\\b|crackle|rhonchi|stethoscope"
 ],
 "Assess/control major bleeding": [
  "bleed|hemorrhag|blood sweep|major bleed|rapid trauma|sweep"
 ],
 "Color": [
  "\\bskin\\b",
  "\\bcolor\\b|\\bpale\\b|cyano|flush|jaundice"
 ],
 "Temperature": [
  "\\bskin\\b",
  "temperature|\\bwarm\\b|\\bcool\\b|\\bcold\\b|\\bhot\\b"
 ],
 "Moisture": [
  "\\bskin\\b",
  "moist|diaphor|sweat|clammy|\\bdry\\b"
 ],
 "Strength (weak, strong, bounding)": [
  "\\bpulse\\b|pulse strength|weak pulse|strong pulse|bounding|thready"
 ],
 "Rate (fast, slow, regular)": [
  "\\bpulse\\b|heart rate|\\bhr\\b|pulse rate|how fast is (the|his|her) (pulse|heart)"
 ],
 "Regularity (regular, irregular)": [
  "\\bpulse\\b|regular pulse|irregular|regularity|rhythm"
 ],
 "Equality (symmetrical, asymmetrical)": [
  "\\bpulse\\b|equal|symmetr|bilateral pulse|both sides|compare (the )?pulses"
 ],
 "Capillary refill": [
  "cap(illary)? refill|\\bcrt\\b|nail bed|blanch"
 ],
 "Identify if patient is in shock": [
  "\\bshock\\b|perfus|compensat|hypoperfusion"
 ],
 "Identify patient priority (stable/unstable) and transport decision": [
  "priority|stable|unstable|transport decision|load and go|stay and play|load & go|how (fast|soon) (do we|should we) (go|transport)|sick or not sick"
 ],
 "Patient priority & transport decision": [
  "priority|stable|unstable|transport decision|load and go|stay and play|load & go|how (fast|soon) (do we|should we) (go|transport)|sick or not sick"
 ],
 "Onset": [
  "\\bonset\\b|when did (it|this|the pain) (start|begin)|sudden|gradual|what were you doing when"
 ],
 "Provocation / palliation": [
  "provo|palliat|make(s)? it (better|worse)|anything help|position help|what makes|worse when|better when"
 ],
 "Quality": [
  "quality|describe (the|your) pain|what does it feel like|\\bsharp\\b|\\bdull\\b|\\bpressure\\b|tearing|crushing|stabbing|aching|burning pain"
 ],
 "Radiation": [
  "radiat|spread|go anywhere|travel|move anywhere|\\bjaw\\b|down (your|the) arm|into (your|the) (arm|back|shoulder)"
 ],
 "Severity": [
  "severity|\\bscale\\b|1 ?(to|-) ?10|out of (10|ten)|how bad|rate (the|your) pain|pain score|zero to ten"
 ],
 "Time": [
  "how long|duration|since when|constant|come(s)? and go(es)?|how long ago|when did (it|this) (start|happen)|time of onset"
 ],
 "Allergies": [
  "allerg"
 ],
 "Medications": [
  "medication|\\bmeds\\b|prescri|what do you take|pills|drugs (do you|does he|does she) take|blood thinner|anticoag|viagra|cialis"
 ],
 "Past pertinent medical history": [
  "history|\\bpmh\\b|\\bhx\\b|medical (problems|conditions|issues)|diagnos|ever had this before|health problems|conditions"
 ],
 "Past pertinent history": [
  "history|\\bpmh\\b|\\bhx\\b|medical (problems|conditions|issues)|diagnos|ever had this before|health problems|conditions"
 ],
 "Last oral intake": [
  "last (ate|eat|drink|drank|meal|oral|food)|oral intake|eaten|when did you (last )?eat|anything to eat"
 ],
 "Events leading up to present illness": [
  "\\bevents?\\b|leading up|what were you doing|before (this|it) (started|happened)|what happened (before|today)|led up"
 ],
 "Events leading up": [
  "\\bevents?\\b|leading up|what were you doing|before (this|it) (started|happened)|what happened (before|today)|led up"
 ],
 "Blood pressure": [
  "blood pressure|\\bbp\\b|\\bpressure\\b|\\bcuff\\b|systolic|diastolic",
  "\\bvitals\\b|vital signs|set of vitals"
 ],
 "Pulse rate and quality": [
  "\\bpulse\\b|heart rate|\\bhr\\b|radial|carotid",
  "\\bvitals\\b|vital signs|set of vitals"
 ],
 "Ventilatory rate and quality": [
  "respiratory rate|resp rate|\\brr\\b|respirations|breathing rate|count (the )?breath",
  "\\bvitals\\b|vital signs|set of vitals"
 ],
 "Blood glucose level": [
  "glucose|\\bbgl\\b|\\bcbg\\b|\\bsugar\\b|glucometer|finger ?stick|\\bd-?stick\\b|blood sugar"
 ],
 "States field impression of patient": [
  "field impression|\\bimpression\\b|working diagnosis|differential|i think (this|it|he|she) (is|has)|what('s| is) (wrong with|going on with) (him|her|them)|my diagnosis"
 ],
 "Determines reassessment frequency & re-evaluates transport decision": [
  "reassess(ment)? (frequency|every|interval)|every (5|15|five|fifteen) min|how often|re-?evaluate transport|reassessment frequency"
 ],
 "Repeats primary assessment": [
  "repeat (the )?primary|primary (survey|assessment) again|re-?do (the )?primary|recheck (the )?abc|abcs again|repeat abc"
 ],
 "Evaluates response to treatments": [
  "response to treatment|is (it|he|she|that) (better|improving|working|helping)|did (it|that) (help|work)|recheck vitals|repeat vitals|reassess vitals|any better|how (do you|are you) feel(ing)? now|feeling better|improv"
 ],
 "Reassesses patient complaints": [
  "reassess (the )?(complaint|pain|chief)|still (hurt|painful|short of breath)|how('s| is) (the|your) (pain|breathing) now|pain now|any change"
 ],
 "Provides accurate verbal report to receiving facility": [
  "radio report|verbal report|\\breport\\b|call (the )?(hospital|er|ed|receiving)|pre-?arrival|notify (the )?(hospital|er|ed)|call it in|hand ?off"
 ],
 "Inspect face & scalp for DCAP-BTLS": [
  "\\bhead\\b|\\bface\\b|scalp|skull|dcap"
 ],
 "Inspect head for bleeding": [
  "head (for )?bleed|scalp bleed|bleeding from (the )?head|blood (in|on) (the )?(hair|scalp|head)"
 ],
 "Inspect for Raccoon Eyes": [
  "raccoon|periorbital|black eyes"
 ],
 "Inspect for Battle's Sign": [
  "battle|behind (the )?ears?|mastoid"
 ],
 "Inspect ears & nose for fluid (CSF, blood)": [
  "\\bcsf\\b|\\bears?\\b|\\bnose\\b|fluid from|drainage|halo test|cerebrospinal"
 ],
 "Inspect mouth (missing teeth, injury, abnormal odors)": [
  "\\bmouth\\b|teeth|odor|\\bsmell\\b|tongue|sputum|soot|singe"
 ],
 "Assess eyes — PEARL": [
  "pearl|pupil|\\beyes?\\b|penlight|perrl"
 ],
 "Palpate facial structures (crepitus, instability, deformity)": [
  "facial (bone|structure)|palpate (the )?face|orbit|zygom|mandible|\\bjaw\\b|maxill|facial (fracture|instability)"
 ],
 "Inspect neck for DCAP-BTLS": [
  "\\bneck\\b"
 ],
 "Inspect neck for bleeding": [
  "neck (for )?bleed|bleeding from (the )?neck"
 ],
 "Inspect for JVD": [
  "\\bjvd\\b|jugular|neck veins?"
 ],
 "Inspect for subcutaneous emphysema on neck": [
  "sub-?q|subcutaneous|emphysema|crepitus (in|on|around) (the )?neck|rice krispies"
 ],
 "Palpate trachea — deviation": [
  "trache|midline|deviat"
 ],
 "Palpate cervical spine — inline, deformity, tenderness, fracture": [
  "c[- ]?spine|cervical|neck (tender|pain)|posterior neck|step[- ]?off|back of (the )?neck"
 ],
 "Inspect chest for DCAP-BTLS": [
  "\\bchest\\b|thorax|\\bribs?\\b|torso|dcap"
 ],
 "Inspect chest for bleeding": [
  "chest (for )?bleed|bleeding from (the )?chest"
 ],
 "Inspect for sucking chest wound on chest": [
  "sucking|open chest|bubbl|hole in (the )?chest|penetrating chest|chest wound"
 ],
 "Inspect for subcutaneous emphysema on chest": [
  "sub-?q|subcutaneous|emphysema|crepitus (in|on|around) (the )?chest|rice krispies"
 ],
 "Inspect for paradoxical movement": [
  "paradox|flail|segment|chest (wall )?move"
 ],
 "Assess rate, tidal volume, rhythm, accessory muscle use": [
  "tidal|chest rise|respiratory rate|resp rate|\\brr\\b|accessory|work of breathing|breathing (rate|effort)|respirations"
 ],
 "Palpate shoulders": [
  "shoulder"
 ],
 "Palpate clavicles": [
  "clavic|collar ?bone"
 ],
 "Palpate sternum": [
  "sternum|sternal|breast ?bone"
 ],
 "Palpate ribs": [
  "\\bribs?\\b|palpate (the )?chest|chest (wall )?(tender|palpat)|press on (the )?chest"
 ],
 "Listen to lung sounds": [
  "\\blungs?\\b|breath sounds|auscultat|listen to (the )?(chest|lungs)|wheez|\\brales\\b|crackle|rhonchi|stethoscope"
 ],
 "Inspect abdomen for DCAP-BTLS": [
  "abdomen|abdom|\\bbelly\\b|stomach|quadrant|dcap"
 ],
 "Inspect abdomen for bleeding": [
  "abdom(en|inal) (for )?bleed|bleeding from (the )?(abdomen|belly|stomach)|belly (for )?bleed"
 ],
 "Inspect for evisceration": [
  "eviscerat|intestines|bowel (out|showing)|organs (out|showing)"
 ],
 "Inspect for bruising around umbilicus (Cullen's)": [
  "cullen|umbilic|belly ?button|navel"
 ],
 "Inspect for bruising on flanks (Grey-Turner's)": [
  "gr[ae]y|turner|flank"
 ],
 "Palpate all four quadrants — rigidity": [
  "rigid|guard|palpate (the |all |four |all four )*(quadrant|abdomen|belly|stomach)|press on (the |his |her )?(belly|abdomen|stomach)|abdom(en|inal) (tender|soft|palpat)|\\bsoft\\b|tender"
 ],
 "Palpate quadrants — pulsating masses": [
  "pulsat|pulsing|\\baaa\\b|aneurysm"
 ],
 "Palpate quadrants — unusual masses": [
  "\\bmass|\\blump|distend|distension|distention"
 ],
 "Inspect pelvis for DCAP-BTLS": [
  "pelvi|\\bhips?\\b|groin|dcap"
 ],
 "Inspect pelvis for bleeding": [
  "pelvi(s|c) (for )?bleed|bleeding from (the )?(pelvis|groin)|groin (for )?bleed"
 ],
 "If male → inspect for priapism": [
  "priap|genital|erection"
 ],
 "Push pelvic bones together and down — crepitus, instability": [
  "pelvic (stab|compress|rock|spring|instab|palpat)|push .*pelvi|press .*pelvi|compress .*pelvi|pelvis (stable|unstable|tender)|iliac|check (the )?pelvis|palpate (the )?pelvis|pelvis"
 ],
 "Inspect lower extremities for DCAP-BTLS": [
  "\\blegs?\\b|lower ext|thigh|femur|\\bknee|\\bshin\\b|ankle|\\bfoot\\b|\\bfeet\\b|\\bcalf\\b|dcap"
 ],
 "Inspect lower extremities for bleeding": [
  "(leg|legs|lower extremit(y|ies)|thigh|femur) (for )?bleed|bleeding from (the )?(leg|legs|thigh)"
 ],
 "Assess each lower extremity for PMS": [
  "\\bpms\\b|\\bcms\\b|\\bcsm\\b|pulse.*motor|motor.*sensor|sensation|wiggle (your )?toes|pedal|dorsalis|distal pulse|can you (feel|move) (your )?(legs?|feet|toes)|numb|tingl"
 ],
 "Palpate down lower extremities — crepitus, instability, deformity": [
  "palpate (down )?(the )?(legs?|lower|thigh|femur)|(legs?|thigh|femur|lower extremit(y|ies)) (for )?(crepitus|deform|instab|tender|fracture)|feel (down )?(the )?legs?|deformity"
 ],
 "Inspect upper extremities for DCAP-BTLS": [
  "\\barms?\\b|upper ext|\\bhands?\\b|wrist|forearm|elbow|finger|dcap"
 ],
 "Inspect upper extremities for bleeding": [
  "(arm|arms|hand|hands|upper extremit(y|ies)|forearm|wrist) (for )?bleed|bleeding from (the )?(arm|arms|hand|wrist)"
 ],
 "Assess each upper extremity for PMS": [
  "\\bpms\\b|\\bcms\\b|\\bcsm\\b|pulse.*motor|motor.*sensor|sensation|squeeze my (hands?|fingers)|grip|radial pulse|can you (feel|move) (your )?(arms?|hands?|fingers)|wiggle (your )?fingers|numb|tingl"
 ],
 "Palpate down upper extremities — crepitus, instability, deformity": [
  "palpate (down )?(the )?(arms?|upper|hands?|forearm)|(arms?|hands?|forearm|wrist|upper extremit(y|ies)) (for )?(crepitus|deform|instab|tender|fracture)|feel (down )?(the )?arms?|deformity"
 ],
 "Inspect posterior for DCAP-BTLS": [
  "posterior|\\bback\\b|log ?roll|roll (him|her|them|the patient)|behind|buttock|exit wound|flip|dcap"
 ],
 "Inspect posterior for bleeding": [
  "(back|posterior) (for )?bleed|bleeding from (the )?back|exit wound|log ?roll"
 ],
 "Inspect for sucking chest wound on back": [
  "sucking|open chest|bubbl|hole in (the )?(chest|back)|exit wound|second (wound|hole)"
 ],
 "Inspect for subcutaneous emphysema on back": [
  "sub-?q|subcutaneous|emphysema|crepitus (in|on|around) (the )?back|rice krispies"
 ],
 "Palpate spine for crepitus, deformity, tenderness": [
  "\\bspine\\b|spinal|vertebra|step[- ]?off|palpate (the )?back|back (tender|pain)|lumbar|thoracic|sacr|down (the|his|her) back"
 ],
 "Chest pain": [
  "chest pain|chest (hurt|tight|discomfort)|pain in (your|the) chest"
 ],
 "Weakness": [
  "\\bweak|tired|fatigue"
 ],
 "Fever": [
  "fever|temperature|\\bhot\\b|chills"
 ],
 "Swollen hands or feet": [
  "swollen|swelling|edema|ankles|puffy"
 ],
 "Cough": [
  "cough"
 ],
 "Respiratory infection / symptoms of one?": [
  "infection|\\bsick\\b|\\bcold\\b|\\bflu\\b|pneumonia|congest|bronchitis|covid"
 ],
 "Cough? Productive? What coughing up?": [
  "productive|sputum|phlegm|mucus|coughing up|cough"
 ],
 "More comfortable in any position?": [
  "position|comfortable|sitting|lying|orthopnea|lie down|lay down"
 ],
 "Look: accessory muscle use": [
  "accessory|retraction|work of breathing|\\bwob\\b|labored|nasal flaring|effort"
 ],
 "Look: tracheal tugging": [
  "tugging|trache"
 ],
 "Look: jugular vein distention (JVD)": [
  "\\bjvd\\b|jugular|neck veins?"
 ],
 "Look: abnormal positioning": [
  "tripod|posture|positioning|leaning|how (is|are) (he|she|they) (sitting|positioned)"
 ],
 "Listen: breath sounds (grunting, wheezing, rales, stridor)": [
  "\\blungs?\\b|breath sounds|auscultat|listen to (the )?(chest|lungs)|wheez|\\brales\\b|crackle|rhonchi|stethoscope",
  "stridor|grunt"
 ],
 "Feel: tracheal deviation": [
  "trache|midline|deviat"
 ],
 "Shortness of breath": [
  "short(ness)? of breath|\\bsob\\b|dyspnea|trouble breathing|hard to breathe|breathing (ok|okay|alright)|breathless"
 ],
 "Dizziness": [
  "dizz|lighthead|faint|syncop|pass(ed)? out|woozy"
 ],
 "Palpitations": [
  "palpitat|racing|flutter|skipping|heart (pound|race)"
 ],
 "Respiratory infection / symptoms?": [
  "infection|\\bsick\\b|\\bcold\\b|\\bflu\\b|pneumonia|congest|bronchitis|covid"
 ],
 "Does pain change with movement or deep breath?": [
  "deep breath|movement|move|pleuritic|breathe in|reproduc|press on (the|your) chest"
 ],
 "Look: JVD": [
  "\\bjvd\\b|jugular|neck veins?"
 ],
 "Look: peripheral edema": [
  "edema|swollen|swelling|ankles|pitting|legs? (swell|puff)"
 ],
 "Look: pursed-lip breathing": [
  "pursed|lips? (when|while) breath"
 ],
 "Look: pink frothy sputum": [
  "frothy|pink|sputum|foam"
 ],
 "Listen: breath sounds": [
  "\\blungs?\\b|breath sounds|auscultat|listen to (the )?(chest|lungs)|wheez|\\brales\\b|crackle|rhonchi|stethoscope"
 ],
 "Headache": [
  "headache|head (hurt|pain)|migraine"
 ],
 "Blurred vision": [
  "vision|blurr|see (ok|okay|double|clearly)|eyesight|double"
 ],
 "Cloudiness or confusion": [
  "confus|cloud|fogg|disorient|clear[- ]headed|thinking (clearly|straight)"
 ],
 "Other noticeable deficits": [
  "deficit|weakness on one side|one[- ]sided|slur|droop|numb|can('t| not) move|trouble (speaking|walking)"
 ],
 "Seeing/hearing things not there?": [
  "hallucinat|seeing things|hearing things|voices|not there"
 ],
 "Want to hurt yourself or others?": [
  "hurt (yourself|himself|herself|others|someone)|suicid|homicid|harm (yourself|others)|self[- ]harm"
 ],
 "Is presentation normal for patient? What is different / when did it begin?": [
  "normal for (him|her|them)|baseline|different (from|than) (usual|normal)|usual self|like this before|acting (normal|different|strange)|last (seen|known) (normal|well)|when did (he|she|they) (start|become)"
 ],
 "Recent drugs or alcohol? When/what/how much?": [
  "drug|alcohol|drink|drunk|\\buse\\b|substance|opioid|heroin|pills|overdose|\\bod\\b"
 ],
 "History of diabetes? Recent blood sugars?": [
  "diabet|insulin|blood sugar|glucose|sugar"
 ],
 "Fever?": [
  "fever|temperature|\\bhot\\b|chills|infection|\\bsick\\b"
 ],
 "Open wounds?": [
  "wound|\\bcut\\b|laceration|injur|bleeding|trauma"
 ],
 "Look: pupils (PEARL)": [
  "pearl|pupil|\\beyes?\\b|penlight|perrl"
 ],
 "Look: drug/alcohol paraphernalia": [
  "paraphernalia|needle|syringe|bottles|pill bottle|drug|alcohol|look around|around the (room|scene|house)"
 ],
 "Look: active seizure": [
  "seiz|convuls|shaking|twitch|postictal|incontinen|tongue bit"
 ],
 "Feel: head injuries": [
  "head injur|\\bhead\\b|scalp|skull|bump|hematoma|palpate (the )?head|trauma to (the )?head"
 ],
 "Feel: PMS (pulse, motor, sensory)": [
  "\\bpms\\b|\\bcms\\b|\\bcsm\\b|pulse.*motor|motor|sensation|sensory|grip|squeeze my|wiggle|numb|tingl|move (your|his|her) (arms?|legs?|hands?|feet)|strength"
 ],
 "Cincinnati Stroke Scale (FAST)": [
  "cincinnati|stroke (scale|assessment|exam)|\\bfast\\b|\\bbe-?fast\\b|smile|arm drift|\\bspeech\\b|repeat (after me|a (sentence|phrase))|hold (your|both) arms|facial droop|stroke"
 ],
 "Smell: fruity/acetone breath": [
  "fruity|acetone|ketone|\\bdka\\b|sweet (smell|breath)|breath (smell|odor)"
 ],
 "Smell: alcohol on breath": [
  "alcohol (on|smell)|smell (of |like )?(alcohol|booze)|breath (smell|odor)|\\bbooze\\b|\\betoh\\b"
 ],
 "Itchiness": [
  "itch|hives|rash|urticaria|welts"
 ],
 "Encountered known allergen?": [
  "allergen|expos|\\bsting|\\bstung|\\bbit(e|ten)\\b|\\bate\\b|\\beat|what did you (eat|touch|take)|contact with|come in contact|new (food|medic)|shellfish|shrimp|peanut|\\bbee"
 ],
 "Taken anything to treat? (EpiPen, inhaler, Benadryl)": [
  "epi-?pen|benadryl|inhaler|taken anything|take anything|treat|antihistamine|diphenhydramine|used (your|the|an) (epi|inhaler)|carry"
 ],
 "New medications, foods, or cleaning products?": [
  "new (medication|meds|food|product|soap|detergent|cleaning)|changed anything|anything new|cleaning product|new (lotion|cosmetic)"
 ],
 "Look: abnormal positioning (tripod, sniffing)": [
  "tripod|sniffing|posture|positioning|leaning|how (is|are) (he|she|they) (sitting|positioned)"
 ],
 "Look: facial swelling": [
  "swell|\\blips?\\b|tongue|\\bface\\b|angioedema|puffy"
 ],
 "Vomiting? Describe; coffee-ground emesis or BRB?": [
  "vomit|coffee|emesis|throw(ing|n)? up|puk|nause"
 ],
 "Unusual bowel habits? Describe; dark tarry stool?": [
  "bowel|stool|melena|tarry|\\bblack\\b|diarrhea|constipat|\\bpoop\\b|bathroom|hematochezia|bloody stool"
 ],
 "Pain with urination? Unusual odors? Urine appearance?": [
  "urin|\\bpee\\b|bladder|dysuria|hematuria"
 ],
 "If female: vaginal discharge? Could be pregnant?": [
  "pregnan|period|discharge|\\blmp\\b|menstrua|vaginal"
 ],
 "Look: discoloration": [
  "discolor|bruis|ecchymo|cullen|grey|gray|turner|flank|color of (the )?(belly|abdomen)"
 ],
 "Look: distention": [
  "distend|distension|distention|bloat|swollen (belly|abdomen)|big belly"
 ],
 "Look: obvious injury": [
  "injur|wound|trauma|scar|dcap|look at (the|his|her) (belly|abdomen|stomach)|expose (the )?(abdomen|belly)"
 ],
 "Look: swelling": [
  "swell|edema|puffy"
 ],
 "Look: visible masses": [
  "\\bmass|\\blump|bulge|pulsat|visible"
 ],
 "Listen: periodic bowel sounds": [
  "bowel sounds|auscultate (the )?(abdomen|belly)|listen to (the |his |her )?(abdomen|belly|stomach)|stethoscope (on|to) (the )?(belly|abdomen)"
 ],
 "Palpate quadrants: tenderness": [
  "tender|palpat|press (on|down)|push on|feel (the |his |her )?(belly|abdomen|stomach)|quadrant|\\bhurt when"
 ],
 "Palpate quadrants: rebound tenderness": [
  "rebound|let go|release|peritoni"
 ],
 "Palpate quadrants: guarding/rigidity": [
  "guard|rigid|\\bsoft\\b|board[- ]?like|tense|firm"
 ],
 "Palpate quadrants: unusual masses": [
  "\\bmass|\\blump|pulsat|\\baaa\\b|aneurysm|bulge"
 ],
 "Chest pain or tightness?": [
  "chest pain|chest (hurt|tight|discomfort)|pain in (your|the) chest|tightness"
 ],
 "Fever, recent illness?": [
  "fever|temperature|chills|\\bsick\\b|\\bcold\\b|\\bflu\\b|illness|infection|pneumonia"
 ],
 "Triggers (allergens, exertion, cold air)": [
  "trigger|allergen|exertion|exercise|cold air|exposure|\\bcats?\\b|\\bdust\\b|\\bpollen\\b|set (it|this) off|what (caused|started)"
 ],
 "Smoking history": [
  "smok|cigarette|vape|tobacco|pack"
 ],
 "Look: tripod position": [
  "tripod|posture|positioning|leaning|how (is|are) (he|she|they) (sitting|positioned)"
 ],
 "Look: cyanosis": [
  "cyano|\\bblue\\b|dusky|lip color|color of (the )?lips"
 ],
 "Listen: wheezing": [
  "\\blungs?\\b|breath sounds|auscultat|listen to (the )?(chest|lungs)|wheez|\\brales\\b|crackle|rhonchi|stethoscope"
 ],
 "Listen: rales/rhonchi": [
  "\\brales\\b|rhonchi|crackle|\\blungs?\\b|breath sounds|auscultat|wet lungs|fluid in (the )?lungs"
 ],
 "Listen: stridor": [
  "stridor|upper airway (sound|noise)|high[- ]pitched|airway (sound|noise)"
 ],
 "Onset / triggering exposure": [
  "\\bonset\\b|when did (it|this) (start|begin)|sudden|gradual|expos|trigger|\\bsting|\\bstung|\\bate\\b|\\beat|allergen|what (caused|started|happened)"
 ],
 "Itching, hives, rash": [
  "itch|hives|rash|urticaria|welts|skin (bump|red)"
 ],
 "Throat tightness / trouble swallowing": [
  "throat|swallow|tight(ness)? in (the|your) throat|closing|voice|hoarse|lump in (the|your) throat"
 ],
 "Wheezing / shortness of breath": [
  "wheez|short(ness)? of breath|\\bsob\\b|dyspnea|trouble breathing|hard to breathe|breathing (ok|okay|alright)|tight chest"
 ],
 "Dizziness / lightheadedness": [
  "dizz|lighthead|faint|syncop|pass(ed)? out|woozy"
 ],
 "Prior reactions / EpiPen use": [
  "prior reaction|before|previous|last time|epi-?pen|carry|history of (allerg|reaction|anaphyl)|anaphyla"
 ],
 "Look: facial/lip/tongue swelling": [
  "swell|\\blips?\\b|tongue|\\bface\\b|angioedema|puffy|\\bmouth\\b"
 ],
 "Look: hives / urticaria": [
  "hives|urticaria|rash|welts|\\bskin\\b|red (blotch|patch)"
 ],
 "Onset of symptoms (gradual vs sudden)": [
  "\\bonset\\b|when did (it|this) (start|begin)|sudden|gradual|how (quickly|fast) did|last (seen|known) (normal|well)|when did (he|she|they) (start|become)"
 ],
 "Headache, vision changes": [
  "headache|head (hurt|pain)|vision|blurr|see (ok|okay|double|clearly)|eyesight"
 ],
 "Recent trauma, fall, head injury": [
  "trauma|\\bfall|\\bfell\\b|head injur|hit (his|her|their) head|\\binjur|bump"
 ],
 "Recent illness, fever, drug/alcohol use": [
  "illness|\\bsick\\b|fever|infection|drug|alcohol|drink|drunk|substance|overdose|\\bod\\b"
 ],
 "Diabetes / insulin / time of last meal": [
  "diabet|insulin|blood sugar|glucose|\\bsugar\\b|last (ate|eat|meal|oral|food)|eaten|when did (he|she|they) (last )?eat|metformin"
 ],
 "Cincinnati Stroke Scale (Face, Arms, Speech, Time)": [
  "cincinnati|stroke (scale|assessment|exam)|\\bfast\\b|\\bbe-?fast\\b|smile|arm drift|\\bspeech\\b|repeat (after me|a (sentence|phrase))|hold (your|both) arms|stroke"
 ],
 "Look: facial droop": [
  "droop|smile|face (symmetr|even)|facial (symmetr|asymmetr)|one side of (the|his|her) face"
 ],
 "Look: posturing / abnormal movements": [
  "postur|decorticate|decerebrate|abnormal move|seiz|twitch|tremor|shaking"
 ],
 "Assess motor — grip strength bilateral": [
  "grip|squeeze (my|both)|motor|strength|arm drift|hold (your|both) arms|move (your|his|her) (arms?|hands?|legs?)|push against"
 ],
 "Assess sensation": [
  "sensation|sensory|\\bfeel (this|that|my)|numb|tingl|can you feel"
 ],
 "Onset of pain (sudden vs gradual)": [
  "\\bonset\\b|when did (it|this|the pain) (start|begin)|sudden|gradual|come on (fast|slow|quick)"
 ],
 "Nausea, vomiting": [
  "nause|vomit|emesis|throw(ing|n)? up|puk|sick to (your|his|her) stomach"
 ],
 "Last bowel movement, melena, hematochezia": [
  "bowel|stool|melena|tarry|\\bblack\\b|diarrhea|constipat|\\bpoop\\b|bathroom|hematochezia|bloody stool"
 ],
 "Hematemesis or coffee-ground emesis": [
  "hematemesis|coffee|vomit(ing|ed)? (up )?blood|blood in (the|his|her|your) vomit|throwing up blood"
 ],
 "Last urination": [
  "urin|\\bpee\\b|bladder|last (went|used) (to )?(the )?bathroom"
 ],
 "Pregnancy possibility (if applicable)": [
  "pregnan|period|\\blmp\\b|menstrua"
 ],
 "Look: distension, scars, bruising": [
  "distend|distension|distention|scar|bruis|ecchymo|cullen|grey|gray|turner|flank|look at (the|his|her) (belly|abdomen|stomach)|expose (the )?(abdomen|belly)|discolor"
 ],
 "Look: pulsating masses (AAA)": [
  "pulsat|pulsing|\\baaa\\b|aneurysm|\\bmass|visible"
 ],
 "Palpate: tenderness by quadrant": [
  "tender|palpat|press (on|down)|push on|feel (the |his |her )?(belly|abdomen|stomach)|quadrant|\\bhurt when|\\bmass|\\blump"
 ],
 "Palpate: rigidity, guarding": [
  "guard|rigid|\\bsoft\\b|board[- ]?like|tense|firm|rebound"
 ],
 "Palpate: pedal pulses bilateral": [
  "pedal|dorsalis|posterior tibial|distal pulse|femoral|pulses? in (the|his|her) (feet|legs)|foot pulse|compare (the )?pulses|\\bpms\\b"
 ]
};
